package com.tts.subscriberlist.subscriber;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import org.hibernate.annotations.CreationTimestamp;
import org.springframework.data.annotation.CreatedDate;

@Entity
public class Subscriber {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO) //allows the id to be generated by the underlying database
	private Long id;
	private String firstName;
	private String lastName;
	private String userName;
	
	@Column
	@CreationTimestamp //allows the date to be generated by the system
	private Date signedUp;
	
	
	//Constructors
	public Subscriber() {
		//non-argument constructor needed for JPA
	}
	
	public Subscriber(Long id, String firstName, String lastName, String userName, Date signedUp) {
		super();
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.userName = userName;
		this.signedUp = signedUp;
	}

	// Getters And Setters
	public Long getId() {
		return id;
	}


	public void setId(Long id) {
		this.id = id;
	}


	public String getFirstName() {
		return firstName;
	}


	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}


	public String getLastName() {
		return lastName;
	}


	public void setLastName(String lastName) {
		this.lastName = lastName;
	}


	public String getUserName() {
		return userName;
	}


	public void setUserName(String userName) {
		this.userName = userName;
	}


	public Date getSignedUp() {
		return signedUp;
	}


	public void setSignedUp(Date signedUp) {
		this.signedUp = signedUp;
	}
	
	// toString Method
	@Override
	public String toString() {
		return "Subscriber [id=" + id + ", firstName=" + firstName + ", lastName=" + lastName + ", userName=" + userName
				+ ", signedUp=" + signedUp + "]";
	}
	

}

